### ISSUE TITLE
Adding source code for CVPR 2019 paper

### ISSUE THREAD

**Issue by os1a** [xuehaouwa/Awesome-Trajectory-Prediction#12]
Hi,

Recently we have published the source code for our CVPR 2019 paper, could you please add the link?
https://github.com/lmb-freiburg/Multimodal-Future-Prediction

Paper: Overcoming Limitations of Mixture Density Networks: A Sampling and Fitting Framework for Multimodal Future Prediction

**Comment by xuehaouwa** [comment]
> Hi,
> 
> Recently we have published the source code for our CVPR 2019 paper, could you please add the link?
> https://github.com/lmb-freiburg/Multimodal-Future-Prediction
> 
> Paper: Overcoming Limitations of Mixture Density Networks: A Sampling and Fitting Framework for Multimodal Future Prediction

Hi, your code link has been added. Thank you very much for reminding me~
